# ===== BUILD STAGE =====
FROM golang:1.25-alpine AS builder

# Forçar IPv4 e usar o proxy oficial
ENV GOPROXY=https://proxy.golang.org,direct

RUN apk add --no-cache gcc musl-dev

WORKDIR /app
COPY go.mod go.sum ./
# Download prévio para cache de camadas
RUN go mod download

# Agora copiamos o código e alinhamos as dependências
COPY . .
RUN go mod tidy
RUN CGO_ENABLED=1 GOOS=linux go build -o /keymanager ./cmd/keymanager

# ===== RUN STAGE =====
FROM alpine:3.19

RUN apk add --no-cache ca-certificates

COPY --from=builder /keymanager /keymanager

EXPOSE 8082

CMD ["/keymanager"]
